# Generated by Django 5.1.6 on 2025-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_job_category_job_deadline_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
